team_codes = {
    'Atlanta Hawks': 0,
    'Boston Celtics': 1,
    'Charlotte Bobcats': 2,
    'Chicago Bulls': 3,
    'Cleveland Cavaliers': 4,
    'Dallas Mavericks': 5,
    'Denver Nuggets': 6,
    'Detroit Pistons': 7,
    'Golden State Warriors': 8,
    'Houston Rockets': 9,
    'Indiana Pacers': 10,
    'Los Angeles Clippers': 11,
    'Los Angeles Lakers': 12,
    'Memphis Grizzlies': 13,
    'Miami Heat': 14,
    'Milwaukee Bucks': 15,
    'Minnesota Timberwolves': 16,
    'New Jersey Nets': 17,
    'New Orleans Pelicans': 18,
    'New York Knicks': 19,
    'Orlando Magic': 20,
    'Philadelphia 76ers': 21,
    'Phoenix Suns': 22,
    'Portland Trail Blazers': 23,
    'Sacramento Kings': 24,
    'San Antonio Spurs': 25,
    'Seattle SuperSonics': 26,
    'Toronto Raptors': 27,
    'Utah Jazz': 28,
    'Washington Wizards': 29
}